### ISSUE TITLE
How do I get a processes' output as a `ByteString`?

### ISSUE THREAD

**Issue by gnull** [nh2/command#2]
I'm trying to extract the output of `tar cf - somefile`, so the stdout of by process will be a binary string. This library seems to allow capturing it only as a `String`. Is it safe to use `String` in my case? Does this library allow reading stdout as `ByteString`?

Ivan

**Comment by nh2** [comment]
Hi, 

> Does this library allow reading stdout as `ByteString`?

no, because at the time I extracted this library as a module from [shake](https://hackage.haskell.org/package/shake), it only supported `String` capture.

However, today, you can instead use the equivalent module from `shake`: [`Development.Shake.Command`](https://hackage.haskell.org/package/shake-0.19.7/docs/Development-Shake-Command.html)

Its [`Stdout`](https://hackage.haskell.org/package/shake-0.19.7/docs/Development-Shake-Command.html#t:Stdout) type was improved to support `ByteString`s via the [`CmdString`](https://hackage.haskell.org/package/shake-0.19.7/docs/Development-Shake-Command.html#t:CmdString) typeclass of which `ByteStrings` are instances.

**Comment by gnull** [comment]
Thank you for the pointer.

Should we keep this Issue open, in case you accept patches for this? One could get add support for `ByteString` by just replicating what `shake` does: making `Stdout` parameterized by the type of the values inside it.

**Comment by nh2** [comment]
On https://hackage.haskell.org/package/command it says

> Deprecated. in favor of [shake](https://hackage.haskell.org/package/shake)

so I think in the past I probably decided that my reason for not being able to use `shake` directly went away.

So I'll go for closing now; if we find a reason why `shake` cannot be used, we might revive this library by re-copy-pasing the current version of the `Command` module from `shake`.
